# Site settings
title:          "Blog"
description:    ""
baseurl:        "" # the subpath of your site
url:            "https://blog.sylva.kr"

# Google Analytics
google_analytics: I edited analytics.html instead of using this setting. Please check _includes/analytics.html for more details. 

# beehiiv Newsletter
beehiiv_form_id: 260f9dcb-4779-4457-938d-1da5faf92f29



# Author
author:
  name:         me
  url:          https://blog.silva.kr
  email:        me@silva.kr

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
